[package]
name = "mdbook-cmdrun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.*"
mdbook = "0.4.*"
serde_json = "1.0.*"
anyhow = "1.0.*"
regex = "1.*.*"